### ISSUE TITLE
求tensorflow2+版模型

### ISSUE THREAD

**Issue by Carlton-Tang** [tal-tech/edu-bert#1]
请问有tensorflow2+版本的模型吗？能否在其基础之上开源一个tensorflow版的模型，用pytorch的去转换到tensorflow版去，虽然转成功，但是里面有些信息丢失了，用起来不正常

**Comment by Liu-lqq** [comment]
> 请问有tensorflow2+版本的模型吗？能否在其基础之上开源一个tensorflow版的模型，用pytorch的去转换到tensorflow版去，虽然转成功，但是里面有些信息丢失了，用起来不正常

好的，我们近一两周会推出相应tensorflow版，到时会告知您

**Comment by Liu-lqq** [comment]
> 请问有tensorflow2+版本的模型吗？能否在其基础之上开源一个tensorflow版的模型，用pytorch的去转换到tensorflow版去，虽然转成功，但是里面有些信息丢失了，用起来不正常

您好，TAL-EduBert的tensorflow版本已提供，详见README.md，也可通过以下地址下载：[tensorflow版](https://ai.100tal.com/download/TAL-EduBERT-TF.zip)

**Comment by Carlton-Tang** [comment]
赞👍，谢谢
