### ISSUE TITLE
可以披露更多的训练细节吗？

### ISSUE THREAD

**Issue by wlhgtc** [tal-tech/edu-bert#2]
很感谢贵司的工作，可以把这样宝贵的模型开源出来。
想咨询一下相关训练细节：
1. 看 [这里](https://github.com/tal-tech/edu-bert/blob/master/examples/finetune_edubert.sh#L4) 是对 BERT 进行了 fine-tune，想问下是基于哪个模型进行的，谷歌 or 哈工大？
2. 是否方便开源语料（部分也可以），方便对语料和任务相关性进行评估。
3. 关于参数的选择是否有相关实验，或者是否考虑以论文行进行发表？

希望予以解答，不胜感激！

**Comment by Liu-lqq** [comment]
> 很感谢贵司的工作，可以把这样宝贵的模型开源出来。
> 想咨询一下相关训练细节：
> 
> 1. 看 [这里](https://github.com/tal-tech/edu-bert/blob/master/examples/finetune_edubert.sh#L4) 是对 BERT 进行了 fine-tune，想问下是基于哪个模型进行的，谷歌 or 哈工大？
> 2. 是否方便开源语料（部分也可以），方便对语料和任务相关性进行评估。
> 3. 关于参数的选择是否有相关实验，或者是否考虑以论文行进行发表？
> 
> 希望予以解答，不胜感激！

感谢关注，是这样的：
1.我们基于的是google开源的bert-base chinese；
2.语料涉及到一些敏感信息，暂时可能不能开源；
3.参数使用的是google bert-base chinese的默认参数。

**Comment by wlhgtc** [comment]
@Liu-lqq  感谢回复，期待后面的工作~
